### ISSUE TITLE
Default cache location is incorrect, does not get created automatically

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/taco-team-build#13]
Repro:

1. Run in an environment without CORDOVA_CACHE or TACO_HOME set
2. Delete your ~/.taco_home folder if it exists
3. Run a build

Expected: ~/.taco_home/node_modules/cordova is created along with ~/.taco_home/node_modules/cordova/&lt;version&gt;/node_modules
Actual: Folder is not created and cache appears to be at "~/.taco_home/node_modules" without the "cordova" folder name and folder is not created

It looks like we need to update moduleCache = cc in ttb-util.js to the following:

    moduleCache = joinAndCreatePath(cc.split(path.sep));
    process.env['CORDOVA_HOME'] = path.join(moduleCache, '_cordova'); // Set platforms to cache in cache location to avoid unexpected results
    process.env['PLUGMAN_HOME'] = path.join(moduleCache, '_plugman'); // Set plugin cache in cache location to 

There is then a bug somewhere that is causing "cordova" to be omitted from the module path.

**Comment by MSLaguana** [comment]
What version of NPM are you using? I'm not sure whether npm 3 causes issues with our cache structure

**Comment by Chuxel** [comment]
To be clear, this isn't related to the taco-cli.  It's taco-team-build which mirrors the taco-cli's npm structure.

We want to keep taco-team-build and the taco-cli caching in the same location for reuse purposes.

**Comment by MSLaguana** [comment]
So there is no dependency on taco-utils / reuse of TacoPackageLoader?

**Comment by Chuxel** [comment]
The code pre-dates that package's existence, so not today. (taco-team-build has been around well before the taco-cli).  Dan is looking at future refactoring along these lines.

**Comment by Chuxel** [comment]
Resolved
