### ISSUE TITLE
Build fails if you try to generate a signed APK without specifying the passwords in build.json, but entering it during the prompt

### ISSUE THREAD

**Issue by geof90** [Microsoft/taco-team-build#4]
I encountered problems when trying to create a signed APK using the gulp build process.

The issue seems to be that with the following build.json config:
```javascript
{
     "android": {
         "release": {
             "keystore": "geoffrey-keys.keystore",
             "storePassword": "",
             "alias": "geoffrey",
             "password" : "",
             "keystoreType": ""
         }
     }
 }
```
that is, if I do not provide the keystore passwords in build.json but only enter it in manually when the gulp dialog prompts you to do so ("Enter keystore password: )", it tells me that my password is wrong even though I have typed it correctly.

The build does work and successfully generate a signed APK only if the passwords are provided in build.json. There is also another strange issue in that the storePassword and the password must be the same, but I think it the same issue can be seen with using the Cordova CLI directly as well.

**Comment by Chuxel** [comment]
Does this still repro?

**Comment by Chuxel** [comment]
Appears to not repro with recent Cordova and Node.js
